name: Workflow to Build and Push Multi-platform

on:

  # push:
  #   branches: [ main ]
  #   paths:
  #     - '**'
  #     - '!.github/workflows/**'
  #     - '!.gitignore'
  #     - '!.dockerignore'
  #     - '!README.md'
  #     - '!LICENSE'
  #     - '!**/docker-compose.yml'

  schedule:
    - cron: '0 0 * * *' # Example: Runs every day at midnight UTC
    # - cron: '0 13 * * *' # Evety day at 13:00 UTC. Every day at 09:00 GMT-4 (Campo Grande/MS) ===> 09 + 4 = 13 UTC

  workflow_dispatch:

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get latest GLPI version
        id: get_latest
        run: |
          LATEST=$(curl -sI https://github.com/glpi-project/glpi/releases/latest | awk -F'/' '/^location/ {sub("\r","",$NF); print $NF }')
          echo "LATEST=$LATEST" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
     
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: jarbelix/glpi-fpm:${{ steps.get_latest.outputs.LATEST }},jarbelix/glpi-fpm:latest
          platforms: linux/amd64, linux/arm64
          push: true
